changelog:
  categories:
    - title: "Breaking changes"
      labels:
        - breaking-change
    - title: "Features"
      labels:
        - enhancement
    - title: "Bug fixes"
      labels:
        - bug
    - title: "Documentation and maintenance"
      labels:
        - documentation
        - chore
      exclude:
        labels:
          - skip-changelog

